dead players removed from game
inf112-v20/biblioteket pull request #138
Opened 2020-04-26 15:01 UTC by MarcusAadnekvam

closes #121 
closes #119 
closes #116

2020-04-26 17:26 UTC, sondr3 requested changes

2020-04-26 17:26 UTC, sondr3 commented on src/main/java/biblioteket/roborally/actors/Actor.java
> +            robot.removeDamageTokens(robot.getNumberOfDamageTokens() - 2);
Hva er greia med at du gjør `-2` her?

2020-04-26 17:26 UTC, sondr3 commented on src/main/java/biblioteket/roborally/actors/Actor.java
> +    private void handleRobotOutOfBounds(int delay, boolean debug) {
JavaDoc må oppdateres.

2020-04-26 17:26 UTC, sondr3 commented on src/main/java/biblioteket/roborally/actors/RobotRenderer.java
> +    public void removePlayer(DirVector oldPosition, TiledMapTileLayer.Cell playerCell) {
JavaDoc.

2020-04-26 17:27 UTC, sondr3 commented
Good shit med ingen SonarQube klager :ok_hand:

2020-04-27 12:22 UTC, MarcusAadnekvam commented on src/main/java/biblioteket/roborally/actors/Actor.java
> +            robot.removeDamageTokens(robot.getNumberOfDamageTokens() - 2);
sjekk issue 79

2020-04-27 13:32 UTC, sondr3 commented on src/main/java/biblioteket/roborally/actors/Actor.java
> +            robot.removeDamageTokens(robot.getNumberOfDamageTokens() - 2);
Ah, da gir det mening. Thanks.

2020-04-27 13:32 UTC, sondr3 approved these changes

2020-04-27 13:33 UTC, merged